# Alag chart = backend ./helm se independent. CI: helm-frontend/values-<dev|staging|uat>.yaml
replicaCount: 2

image:
  repository: chatappregsistry.azurecr.io/frontend-app
  pullPolicy: IfNotPresent
  tag: "dev-latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
  annotations: {}

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts: []
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: ""

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 3
  periodSeconds: 5
